version: '2'
services:
  target-redshift:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      REDSHIFT_HOST: "${REDSHIFT_HOST}"
      REDSHIFT_DATABASE: "${REDSHIFT_DATABASE}"
      REDSHIFT_SCHEMA: "${REDSHIFT_SCHEMA}"
      REDSHIFT_PORT: "${REDSHIFT_PORT}"
      REDSHIFT_USERNAME: "${REDSHIFT_USERNAME}"
      REDSHIFT_PASSWORD: "${REDSHIFT_PASSWORD}"
      TARGET_S3_AWS_ACCESS_KEY_ID: "${TARGET_S3_AWS_ACCESS_KEY_ID}"
      TARGET_S3_AWS_SECRET_ACCESS_KEY: "${TARGET_S3_AWS_SECRET_ACCESS_KEY}"
      TARGET_S3_BUCKET: "${TARGET_S3_BUCKET}"
      TARGET_S3_KEY_PREFIX: "${TARGET_S3_KEY_PREFIX}"

    volumes:
      - .:/code
